# travis CI script
os: linux
language: cpp
compiler: gcc
sudo: required
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-5

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

